services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:

